### ISSUE TITLE
Config menu not showing up?

### ISSUE THREAD

**Issue by TriforceCreeper** [shadowhunt22/armor-indicator#1]
I'm using version 1.0.0 of the mod on 1.20.4, and when I hover my mouse over the mod in mod menu, the button to open the config menu doesn't show up. I have already checked to make sure I have cloth config API installed.

**Comment by shadowhunt22** [comment]
See this thread on the Discord server:

https://discord.com/channels/1190108027626459246/1238140000504123413/1238144277540896869
