### ISSUE TITLE
Indicator doesnt hide when pressing F1, it stays on screen

### ISSUE THREAD

**Issue by LadyHaley** [shadowhunt22/armor-indicator#3]
Indicator doesnt hide when pressing F1, it stays on screen
All elements of the HUD should be hidden when using F1

**Comment by shadowhunt22** [comment]
Not sure what the issue is here.  I pressed `F1` and the indicator hides.  However, I have made it so the Indicator hides when you press `F3`.

**Comment by LadyHaley** [comment]
Whatever was done in the current version fixed my issue with the indicators not vanishing with F1
