### ISSUE TITLE
Offhand indicator option

### ISSUE THREAD

**Issue by LadyHaley** [shadowhunt22/armor-indicator#5]
Id like to see stats on my left hand item sometimes :3

**Comment by shadowhunt22** [comment]
Heyo!  Thanks for these suggestions and the bug of the HUD not disabling when F1 is pressed!

I am currently rewriting the mod because the code is spaghetti code right now.  Once I am finished with that, I will work on adding these features and fixing bugs!

**Comment by shadowhunt22** [comment]
Feature added: https://modrinth.com/mod/armor-indicator/versions
